---

- name: building images
  hosts: hosts
  vars:
          ansible_ssh_private_key_file: ~/mesl.pem
  roles:
          - role: image

- name: building images with different host
  hosts: hosts
  vars:
         ansible_ssh_private_key_file: ~/mesl.pem
  roles:
          - role: image

- name: create the deployment
  hosts: hosts
  vars:
          ansible_ssh_private_key_file: ~/mesl.pem
  roles:
          - role: deploy 
